### ISSUE TITLE
Working hours and hours worked

### ISSUE THREAD

**Issue by carmenfdezb** [olpeh/wht#19]
It would be very useful for me if you add working hours and hours I've worked, to know how many hours I've worked too much or how many hours I must recover hours.

**Comment by ojhaapala** [comment]
Yes. I have been thinking about it, but there are so many different requirements in different companies. 
To start with I'll probably just create simple calculations per week and month.

**Comment by olpeh** [comment]
Too complicated to implement in order to satisfy all different environments and companies and legislations.
