### ISSUE TITLE
Sending report by mail seems to be broken

### ISSUE THREAD

**Issue by haelge** [olpeh/wht#36]
The "send by mail" feature in the day, week, month and year view is broken. The export as csv feature works properly. Neither the mail app starts, nor a popup appears. The terminal output is: "[W] unknown:104 - file:///usr/share/harbour-workinghourstracker/qml/pages/All.qml:104: ReferenceError: getProject is not defined"

**Comment by olpeh** [comment]
Thanks for reporting. I most probably refactored some code and either renamed or moved the getProject logic somewhere. Should be simple to fix.
