### ISSUE TITLE
Allow user to give project / tasks default descriptions

### ISSUE THREAD

**Issue by Acce0ss** [olpeh/wht#39]
Currently the previous given description is shown for new records. While good for projects with long tasks, sometimes annoying when working on projects with many smaller tasks.

Default text would allow user to start writing right away, instead of first deleting everything.

**Comment by Acce0ss** [comment]
Work on this has already started in https://github.com/olpeh/wht/commit/10ad2b88737216bf132543b62e58aa905b0b44fb

**Comment by olpeh** [comment]
It should set the description according to the last description used in selected task. So if you have a project with several small tasks, you can set them to the project in settings and then when adding hours you could select a task and the description should be set to the last description used in that task. There might still be bugs in this behaviour.

BUT: When focusing the description input area, it should select all the text so that it would be easier to delete it, right?

**Comment by olpeh** [comment]
Just to clarify. It would be a nice feature to set default task for project and also default description for a task.

**Comment by Acce0ss** [comment]
Perhaps I use the tasks differently, but my workflow has been such that I define a project, then a number of generic tasks (e.g. documenting, coding, researching), and then use the description to be more specific about what was done. I often change the description, so if the last description is for example "Worked on featureX doing this and that", next time it might be featureY and I have to delete the text first. This probably was not clear from my first message.

So, "When focusing the description input area, it should select all the text so that it would be easier to delete it, right?"
This would be useful, yes. Or even a clear button, which clears the text, focuses the text field and opens the keyboard.

**Comment by olpeh** [comment]
Alrighty then. That's pretty easy to implement. 
Take a look at this also:
https://github.com/olpeh/wht/issues/15

**Comment by olpeh** [comment]
Might have to take a closer look at this at some point but for now I just added focusing all of the description text so that it's easier to clear it.

**Comment by olpeh** [comment]
@Acce0ss Selecting all the description text on focus is now released in v.1.2.0. It's currently available in openrepos, you might want to update from there.
