### ISSUE TITLE
Integration with online Trackers, such as Redmine

### ISSUE THREAD

**Issue by cnlpete** [olpeh/wht#45]
Ability to sync Projects with Tasks from them
- upload entered times from the report view

**Comment by olpeh** [comment]
I'm currently working on a web based tracking system and an android client to it. Will also integrate WHT to that system (optional to use though, will be free for personal use). However, I will not be able to integrate WHT into it before autumn.

**Comment by olpeh** [comment]
This will not happen in the near future.
