### ISSUE TITLE
Project/task not selected when editing entry

### ISSUE THREAD

**Issue by krzyc** [olpeh/wht#69]
On Sailfish 3.1 (XA2) project/task fields do not update when editing project because of 'Error: Cannot assign to non-existent property "_updating"'. I am using app version 1.3.7-1 from Harbour.

Removing _updating = false definition it works fine. I can submit patch.

**Comment by zagrim** [comment]
I also ran into this yesterday, after having been upgraded to SFOS 3.1. Good to see someone already found the fix.

**Comment by krzyc** [comment]
I have contacted author and project is still active, so fix will be merged soon.

**Comment by olpeh** [comment]
Hey, thanks for the report. Did you manage to submit a PR? I can't see it.
