### ISSUE TITLE
Adjusting start time to yesterday when timer is running not possible

### ISSUE THREAD

**Issue by Pohli** [olpeh/wht#80]
Reproduce: Start timer, tap on Started/Adjust button, set a time later than now (meaning that time yesterday), Accept ⇒ Duration has negative value.
If I start timer at 1:30 for example but started work actually 2 hours before it's impossible to correct to the start time 23:30 of yesterday.

Jolla Phone with SFOS 3.0.1.11 and WHT 1.3.11-1

**Comment by olpeh** [comment]
I see how this is an annoying bug, but with the current codebase and crappy data modeling, this is almost impossible to fix without a complete rewrite of the application.
