### ISSUE TITLE
AAarch64 builds

### ISSUE THREAD

**Issue by motoz** [olpeh/wht#82]
I suppose there are no AAarch64 builds available yet (since there is no 'install' menu in the storeman client on an xperia 10 II). Would it be possible to upload a 64bit build of this awesome software to openrepos?

**Comment by olpeh** [comment]
Yes there is no build available yet because I was unable to create it as you can see here https://forum.sailfishos.org/t/aarch64-apps-in-harbour/3606/5

I should try again

**Comment by ahaaje** [comment]
Please do, and publish it to the Store. Would love to have this available on the Xperia 10 II.

**Comment by motoz** [comment]
I just checked, after installing all updates there is a SailfishOS-latest-aarch64 build target in the maintenance tool. (I have the sdk installed but I haven't ever gotten around to trying to use it in any way...)

**Comment by motoz** [comment]
So I gathered some courage and cloned your repo today, opened the project in the sdk, added the aarch64 target and clicked build and deploy. And bam, there I had working aarch64 build! Now I can finally shut down and retire my old Xperia X. Thanks for this great app, it's exactly what I need when working from home.

**Comment by ahaaje** [comment]
Is there any chance of seeing this in the Jolla store for 64 bit version soon?

**Comment by olpeh** [comment]
Yes, that's possible. Unfortunately, I have been and still am on my summer vacation and trying to avoid computers. Will get back to business later this week.

**Comment by poetaster** [comment]
a bump? I can help getting wht into chum for automated builds, if you wish?

**Comment by olpeh** [comment]
Thanks for the bump. Reinstalling the SDK now as we speak in order to be able to create the build. 
I'll also try to pull the latest translations and then make a release. 

I'd be interested in automating the builds, current solution requires quite a lot of manual work.

**Comment by olpeh** [comment]
Sorry for the loooong delay. Now available in openrepos: https://openrepos.net/content/olpe/working-hours-tracker, submitted to Harbour QA now.

**Comment by poetaster** [comment]
I did test builds here: https://build.sailfishos.org/package/live_build_log/home:poetaster/wht/3.4.0.24_armv7hl/armv8el

Project ERROR: Unknown module(s) in QT: dbus

I think you only need to declare a BuildRequires to get rid of that error and it should just work. In the .spec file:
BuildRequires:  pkgconfig(Qt5DBus)

This build was done directly from your repo using a simple service file: https://build.sailfishos.org/package/view_file/home:poetaster/wht/_service?expand=1

If you add the BuildRequires, give me a nudge and I'll rebuild. 

If you want it in chum, the chum packages are tied to tags/releases and I'd need to know when you bump the release.

Hope that helps.
