### ISSUE TITLE
German locale files de and de-DE?

### ISSUE THREAD

**Issue by donni106** [olpeh/wht#84]
I am about to update locales. @olpeh why are there two German files for the store and for the app, `de` and `de_DE`? And why were there contents different? I assume they should be identical?

**Comment by olpeh** [comment]
Hey, that I don't know, but please do not update those files in the repository, these files are automatically pulled from transifex. 

https://www.transifex.com/projects/p/working-hours-tracker/ you can contribute to translations there by requesting translator access.

**Comment by olpeh** [comment]
Alright, no worries
